const rooms = {};

/*
rooms["room0"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
*/
rooms["room1"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","help","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","help","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","help","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","help","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","help","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room2"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","help","disp","disp","disp","disp","help","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","help","disp","disp","disp","disp","help","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room3"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","help","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","disp","disp","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","help","disp","help","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","disp","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","help","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","help","disp","disp","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room4"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","disp","disp","    ","    ","    ","    ","    ","    ","disp","disp","wall"],
        ["wall","    ","disp","disp","    ","    ","    ","    ","disp","help","    ","wall"],
        ["wall","    ","    ","help","disp","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","help","help","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","help","help","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","help","disp","    ","    ","    ","    ","help","disp","    ","wall"],
        ["wall","disp","disp","    ","    ","    ","    ","    ","    ","disp","disp","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room5"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","disp","disp","disp","    ","    ","    ","help","disp","help","disp","wall"],
        ["wall","help","    ","help","disp","disp","disp","disp","    ","    ","disp","wall"],
        ["wall","disp","    ","disp","    ","    ","    ","    ","    ","disp","disp","wall"],
        ["wall","disp","    ","disp","disp","    ","    ","    ","    ","disp","    ","wall"],
        ["wall","disp","    ","    ","help","    ","    ","    ","disp","help","disp","wall"],
        ["wall","help","disp","    ","disp","    ","    ","disp","disp","    ","disp","wall"],
        ["wall","    ","disp","    ","disp","disp","    ","disp","    ","    ","disp","wall"],
        ["wall","    ","help","    ","    ","help","    ","help","    ","    ","help","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room6"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","help","    ","    ","disp","help","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","help","disp","    ","    ","help","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","help","    ","    ","disp","help","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","help","disp","    ","    ","help","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room7"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","disp","help","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","disp","help","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","    ","disp","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","help","    ","disp","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","disp","disp","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","help","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","disp","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room8"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","help","disp","disp","disp","disp","disp","disp","disp","disp","help","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","help","disp","disp","disp","disp","disp","disp","disp","disp","help","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room9"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","help","disp","disp","disp","disp","disp","disp","disp","disp","help","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","disp","help","disp","disp","disp","disp","help","disp","    ","wall"],
        ["wall","    ","disp","    ","    ","    ","    ","    ","    ","disp","    ","wall"],
        ["wall","    ","disp","    ","    ","    ","    ","    ","    ","disp","    ","wall"],
        ["wall","    ","disp","help","disp","disp","disp","disp","help","disp","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","help","disp","disp","disp","disp","disp","disp","disp","disp","help","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room10"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","help","wall"],
        ["wall","    ","help","disp","disp","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","    ","disp","    ","help","    ","    ","help","    ","    ","disp","wall"],
        ["wall","    ","disp","    ","disp","    ","disp","disp","disp","    ","disp","wall"],
        ["wall","    ","disp","    ","disp","    ","disp","    ","disp","    ","disp","wall"],
        ["wall","    ","disp","    ","disp","    ","disp","    ","disp","disp","help","wall"],
        ["wall","    ","disp","    ","disp","    ","help","    ","    ","    ","    ","wall"],
        ["wall","    ","disp","    ","disp","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","disp","    ","help","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","help","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room11"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","help","    ","    ","    ","    ","    ","    ","    ","    ","help","wall"],
        ["wall","disp","    ","disp","disp","disp","disp","help","disp","    ","disp","wall"],
        ["wall","disp","    ","help","    ","disp","disp","    ","disp","    ","disp","wall"],
        ["wall","disp","    ","disp","    ","disp","disp","    ","disp","    ","disp","wall"],
        ["wall","disp","    ","disp","    ","disp","disp","    ","disp","    ","disp","wall"],
        ["wall","disp","    ","disp","    ","disp","disp","    ","help","    ","disp","wall"],
        ["wall","disp","    ","disp","    ","disp","disp","    ","disp","    ","disp","wall"],
        ["wall","disp","    ","disp","    ","disp","disp","    ","disp","    ","help","wall"],
        ["wall","help","disp","disp","    ","disp","disp","    ","disp","disp","disp","wall"],
        ["wall","    ","    ","    ","    ","help","help","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room12"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","disp","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","    ","disp","disp","    ","    ","disp","disp","disp","    ","disp","wall"],
        ["wall","    ","    ","disp","help","disp","disp","    ","help","    ","disp","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","disp","    ","help","wall"],
        ["wall","    ","disp","disp","disp","    ","disp","    ","disp","disp","disp","wall"],
        ["wall","    ","disp","    ","disp","    ","disp","    ","    ","    ","    ","wall"],
        ["wall","disp","help","    ","disp","disp","help","disp","disp","    ","    ","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","disp","disp","    ","    ","    ","disp","disp","disp","disp","    ","wall"],
        ["wall","    ","help","    ","    ","    ","help","    ","    ","help","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room13"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","disp","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","disp","    ","    ","    ","    ","disp","disp","disp","    ","wall"],
        ["wall","    ","help","disp","disp","    ","    ","disp","    ","help","    ","wall"],
        ["wall","    ","    ","    ","disp","help","    ","disp","    ","disp","    ","wall"],
        ["wall","    ","    ","    ","disp","    ","    ","disp","    ","disp","disp","wall"],
        ["wall","    ","    ","disp","disp","    ","    ","help","    ","    ","disp","wall"],
        ["wall","    ","    ","help","    ","    ","    ","disp","    ","    ","disp","wall"],
        ["wall","    ","    ","disp","disp","disp","disp","disp","    ","    ","disp","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","disp","disp","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","help","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room14"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","help","    ","    ","help","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","help","    ","    ","help","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","    ","    ","disp","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","help","    ","    ","help","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room15"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","help","    ","    ","    ","wall"],
        ["wall","disp","disp","disp","disp","disp","    ","disp","disp","disp","disp","wall"],
        ["wall","disp","help","    ","    ","disp","    ","    ","    ","    ","disp","wall"],
        ["wall","disp","    ","    ","disp","help","    ","disp","help","disp","disp","wall"],
        ["wall","disp","    ","    ","disp","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","disp","disp","    ","disp","disp","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","disp","    ","    ","disp","    ","help","    ","    ","    ","wall"],
        ["wall","    ","disp","    ","    ","disp","disp","disp","    ","    ","    ","wall"],
        ["wall","disp","disp","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","help","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room16"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","help","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","disp","disp","disp","wall"],
        ["wall","    ","    ","    ","disp","disp","disp","disp","    ","disp","    ","wall"],
        ["wall","help","disp","disp","disp","    ","disp","    ","    ","disp","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","disp","    ","    ","disp","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","disp","    ","    ","disp","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","disp","    ","    ","disp","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","disp","    ","    ","disp","    ","wall"],
        ["wall","    ","    ","disp","    ","    ","disp","    ","    ","disp","    ","wall"],
        ["wall","    ","    ","help","    ","    ","help","    ","    ","help","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room17"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","help","help","    ","    ","    ","    ","wall"],
        ["wall","disp","disp","disp","disp","disp","disp","disp","disp","disp","disp","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","help","disp","    ","    ","    ","    ","    ","    ","disp","help","wall"],
        ["wall","    ","disp","    ","    ","    ","    ","    ","    ","disp","    ","wall"],
        ["wall","    ","disp","disp","disp","disp","disp","disp","disp","disp","    ","wall"],
        ["wall","    ","    ","help","disp","    ","    ","disp","help","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","    ","    ","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","disp","help","help","disp","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room18"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","disp","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","disp","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","help","disp","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","help","disp","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","disp","disp","    ","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","disp","disp","    ","    ","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","disp","disp","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room19"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","help","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","    ","    ","disp","disp","help","disp","disp","disp","disp","help","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","disp","wall"],
        ["wall","disp","disp","disp","disp","disp","help","disp","    ","    ","disp","wall"],
        ["wall","disp","    ","    ","    ","    ","    ","disp","    ","    ","disp","wall"],
        ["wall","help","    ","disp","disp","help","    ","disp","disp","disp","disp","wall"],
        ["wall","disp","    ","help","    ","disp","    ","    ","    ","    ","    ","wall"],
        ["wall","disp","disp","disp","    ","disp","    ","    ","disp","disp","disp","wall"],
        ["wall","    ","    ","    ","    ","disp","disp","help","disp","    ","disp","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","help","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}
rooms["room20"] = {
    grid: [
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
        ["wall","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","saf1","wall"],
        ["wall","    ","    ","    ","    ","    ","    ","    ","    ","    ","help","wall"],
        ["wall","disp","disp","disp","disp","    ","help","disp","disp","disp","disp","wall"],
        ["wall","help","    ","    ","disp","disp","disp","    ","    ","disp","    ","wall"],
        ["wall","disp","disp","    ","    ","    ","    ","    ","    ","disp","disp","wall"],
        ["wall","    ","disp","    ","disp","disp","disp","disp","    ","    ","disp","wall"],
        ["wall","    ","disp","    ","disp","    ","    ","disp","help","    ","disp","wall"],
        ["wall","    ","disp","    ","help","    ","    ","    ","disp","    ","disp","wall"],
        ["wall","    ","disp","    ","disp","    ","    ","    ","disp","    ","help","wall"],
        ["wall","disp","disp","disp","disp","    ","    ","    ","disp","disp","disp","wall"],
        ["wall","help","    ","    ","    ","    ","    ","    ","    ","    ","    ","wall"],
        ["wall","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","saf2","wall"],
        ["wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall","wall"],
    ],
}